name: tarsier_env
description: A Dart/Flutter package for loading `.env` files and simplifies the management of environment variables and helps automate the process of accessing them within your project.
version: 1.0.3
homepage: https://github.com/marianz-bonfire/tarsier_env
repository: https://github.com/marianz-bonfire/tarsier_env
issue_tracker: https://github.com/marianz-bonfire/tarsier_env/issues

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
